---
title: "test_run"
author: "Peter Lin"
date: "April 9, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r}
library(LufthansaR)
library(jsonlite)
library(lubridate)
```

```{r}
response <- read_json("../response.JSON")
```


```{r}

LUFTHANSA_API_CLIENT_ID <- "j886rwc554tcyzmhsqk65bgb"

LUFTHANSA_API_CLIENT_SECRET <- "jkUMzE52bQ"

token <- "nvr5c5bv7rnqrkvef5ufmm9v"

tm <- as.POSIXlt(Sys.time(), tz="Europe/Berlin", "%Y-%m-%dT%H:%M")
tm_FRA <- strftime(tm,  "%Y-%m-%dT%H:%M")
# to parse the content
```



```{r}

if (response$FlightStatusResource$Meta$TotalCount == 1){
  (no_flight_returned <-response$FlightStatusResource$Meta$TotalCount)
} else{
  (no_flight_returned <- summary(response$FlightStatusResource$Flights)[1])
}
```

```{r}

if(!(is.nan(no_flight_returned) | no_flight_returned <= 1)){
  flight_departure_data <- data.frame(flight_code = rep(NA, no_flight_returned), 
            scheduled_dept =rep(NA, no_flight_returned), destination_airport =rep(NA, no_flight_returned), arrival_time =rep(NA, no_flight_returned))
  
  for (i in 1:no_flight_returned){
  
    flight_departure_data$flight_code[i] <- 
      paste0( response$FlightStatusResource$Flights[[1]][[i]]$MarketingCarrier$AirlineID,response$FlightStatusResource$Flights[[1]][[i]]$MarketingCarrier$FlightNumber)
  
    flight_departure_data$scheduled_dept[i] <-  
      response$FlightStatusResource$Flights[[1]][[i]]$Departure$ScheduledTimeLocal$DateTime
  
    flight_departure_data$destination_airport[i] <- response$FlightStatusResource$Flights[[1]][[i]]$Arrival$AirportCode
    
    flight_departure_data$arrival_time[i] <- response$FlightStatusResource$Flights[[1]][[i]]$Arrival$ScheduledTimeLocal
  }
flight_departure_data
  
} else {
  print("No flight information available at this time!")
}

ggsave("flight_arrival_viz.png", device = "png",  plot = last_plot())
```

```{r}
flight_departure_data$arrival_time <- unlist(flight_departure_data$arrival_time)
write.csv(flight_departure_data, file = "flight_departure_data.csv")
```
